kind: pipeline
name: docker-build

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**


steps:
  - name: docker-build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: registry.sighup.io/delivery/fury-getting-started
      tags:
        - ${DRONE_TAG}
      dockerfile: ./utils/docker/Dockerfile
