kind: pipeline
name: docker-build

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**


steps:
  - name: docker-build
    image: plugins/docker
    privileged: true
    environment:
      HOME: "/tmp"
    settings:
      debug: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.sighup.io
      repo: registry.sighup.io/delivery/fury-getting-started
      tags:
        - ${DRONE_TAG}
      dockerfile: ./utils/docker/Dockerfile
