resources:

  # Monitoring module
  - ../vendor/katalog/monitoring/prometheus-operator
  - ../vendor/katalog/monitoring/prometheus-operated
  - ../vendor/katalog/monitoring/alertmanager-operated
  - ../vendor/katalog/monitoring/node-exporter
  - ../vendor/katalog/monitoring/kube-state-metrics
  - ../vendor/katalog/monitoring/grafana
  - ../vendor/katalog/monitoring/goldpinger
  - ../vendor/katalog/monitoring/configs

  # Logging module
  - ../vendor/katalog/logging/elasticsearch-single
  - ../vendor/katalog/logging/fluentd
  - ../vendor/katalog/logging/kibana

  # Ingress module
  - ../vendor/katalog/ingress/nginx
  - ../vendor/katalog/ingress/forecastle

  # Ingress definitions
  - resources/ingress.yml

patchesStrategicMerge:

  - patches/monitoring/alertmanager-operated-replicas.yml
  - patches/monitoring/alertmanager-operated-resources.yml
  - patches/monitoring/prometheus-operated-resources.yml
  - patches/monitoring/prometheus-operator-resources.yml
  - patches/monitoring/grafana-resources.yml
  - patches/logging/fluentd-resources.yml
  - patches/logging/kibana-resources.yml
  - patches/logging/fluentbit-resources.yml
  - patches/logging/elasticsearch-resources.yml
  - patches/ingress/nginx-ingress-controller-resources.yml